# --- QTRAN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000

runner: "episode"
batch_size_run: 1
buffer_size: 64
batch_size: 128
optimizer: 'adam'

t_max: 1000000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent: "n_rnn"
agent_output_type: "q"
learner: "qtran_learner"
double_q: True
mixer: "qtran"
mixing_embed_dim: 64
qtran_arch: "qtran_paper"

opt_loss: 1
nopt_min_loss: 0.1

network_size: small

name: "qtran_env"
